# Generated by Django 5.2.15 on 2026-06-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("client_name", models.CharField(max_length=255)),
                ("matter_type", models.CharField(max_length=255)),
                ("jurisdiction", models.CharField(max_length=255)),
                ("posture", models.CharField(blank=True, max_length=255)),
                ("risk", models.CharField(blank=True, max_length=120)),
                ("summary", models.TextField(blank=True)),
                (
                    "source_system",
                    models.CharField(default="LegalServer", max_length=120),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["client_name"],
            },
        ),
        migrations.CreateModel(
            name="MatterFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("source_label", models.CharField(max_length=255)),
                ("confidence", models.CharField(default="candidate", max_length=80)),
                ("ai_suggested", models.BooleanField(default=False)),
                ("selected_by_default", models.BooleanField(default=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("matter", "slug")},
            },
        ),
    ]
