# Generated by Django 5.2.15 on 2026-06-26 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_cleveland_rtc_rubric(apps, _schema_editor):
    TriageRubric = apps.get_model('matters', 'TriageRubric')
    TriageRubric.objects.get_or_create(
        slug='cleveland-rtc-priority',
        defaults={
            'name': 'Cleveland Right to Counsel priority',
            'description': "Initial screening for priority full-representation cases under Cleveland eviction Right to Counsel intake rules.",
            'standard': (
                "Classify whether this housing matter appears to be a priority case for full representation "
                "under Cleveland's eviction Right to Counsel screening rules. Treat the case as priority when "
                "the tenant or household appears to be in an eviction or displacement matter in Cleveland or "
                "Cuyahoga County and has indicators commonly used for full-representation triage, including "
                "children in the household, very low income, subsidy or voucher risk, disability, domestic "
                "violence or safety concerns, imminent lockout/hearing/default, conditions affecting health, "
                "or other severe housing-stability risk. Mark as needs review when eligibility facts are missing."
            ),
            'criteria': [
                'Eviction, termination, lockout, or displacement risk',
                'Cleveland or Cuyahoga County housing forum',
                'Children, disability, senior, pregnancy, or other vulnerable household member',
                'Subsidized housing, voucher, public housing, or rental assistance at risk',
                'Imminent hearing, lockout, default, or deadline',
                'Health/safety conditions, domestic violence, retaliation, or discrimination concerns',
                'Income or other facts suggesting Right to Counsel eligibility',
            ],
            'active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('standard', models.TextField()),
                ('criteria', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, max_length=255)),
                ('priority', models.BooleanField(default=False)),
                ('priority_label', models.CharField(blank=True, max_length=120)),
                ('confidence', models.CharField(default='needs_review', max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('matched_criteria', models.JSONField(blank=True, default=list)),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('llm_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='matters.matter')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='matters.triagerubric')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_cleveland_rtc_rubric, migrations.RunPython.noop),
    ]
