# Generated by Django 5.2.15 on 2026-08-11 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_triagerubric_triageassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalServerDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('casenote', 'Case note'), ('document', 'Document'), ('case_update', 'Case property update')], max_length=40)),
                ('origin', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('saved', 'Saved to LegalServer'), ('skipped', 'Not sent'), ('failed', 'Failed'), ('dry_run', 'Previewed only')], max_length=40)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('filename', models.CharField(blank=True, max_length=500)),
                ('remote_id', models.CharField(blank=True, max_length=255)),
                ('remote_url', models.URLField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legalserver_deliveries', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legalserver_deliveries', to='matters.matter')),
            ],
            options={
                'verbose_name_plural': 'LegalServer deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
