# Generated by Django 5.2.15 on 2026-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0003_legalserverdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalserverdelivery',
            name='scope_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='legalserverdelivery',
            name='updated_existing',
            field=models.BooleanField(default=False),
        ),
    ]
