# Generated by Django 5.2.15 on 2026-09-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0004_legalserverdelivery_scope_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterRouteAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=120)),
                ('alias', models.CharField(max_length=120)),
                ('normalized_alias', models.CharField(max_length=120, unique=True)),
                ('is_current', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_aliases', to='matters.matter')),
            ],
            options={
                'verbose_name_plural': 'matter route aliases',
                'ordering': ['-is_current', '-last_seen_at'],
            },
        ),
    ]
