# Generated by Django 5.2.15 on 2026-06-24 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_type', models.CharField(max_length=50)),
                ('citation', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=500)),
                ('pinpoint', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['authority_type', 'citation', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DecisionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('court_scope', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=50)),
                ('hit_policy', models.CharField(choices=[('collect', 'Collect'), ('first', 'First'), ('unique', 'Unique'), ('priority', 'Priority')], default='collect', max_length=50)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('engine_type', models.CharField(choices=[('dmn_lite', 'DMN-lite'), ('jsonlogic', 'JSONLogic'), ('blawx', 'Blawx')], default='dmn_lite', max_length=50)),
                ('external_ruleset_ref', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('authorities', models.ManyToManyField(blank=True, to='rules.ruleauthority')),
            ],
            options={
                'ordering': ['key', '-version'],
                'unique_together': {('key', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DecisionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inputs', models.JSONField()),
                ('expected_outputs', models.JSONField()),
                ('enabled', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='rules.decisiontable')),
            ],
            options={
                'ordering': ['table__key', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255)),
                ('workflow_run_id', models.CharField(blank=True, max_length=255)),
                ('table_key', models.SlugField()),
                ('table_version', models.PositiveIntegerField()),
                ('input_snapshot', models.JSONField()),
                ('matched_rows', models.JSONField(default=list)),
                ('outputs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['case_id', 'workflow_run_id'], name='rules_ruler_case_id_104de9_idx'), models.Index(fields=['table_key', 'table_version'], name='rules_ruler_table_k_f8571d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DecisionRuleRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.SlugField()),
                ('label', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=100)),
                ('conditions', models.JSONField()),
                ('outputs', models.JSONField()),
                ('explanation_template', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='rules.decisiontable')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'unique_together': {('table', 'row_id')},
            },
        ),
    ]
