# Generated by Django 5.2.15 on 2026-09-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_seed_eviction_answer_issue_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('court_type', models.CharField(choices=[('municipal', 'Municipal court'), ('county', 'County court'), ('common_pleas', 'Court of common pleas'), ('appellate', 'Court of appeals'), ('supreme', 'Supreme court'), ('federal_district', 'Federal district court'), ('federal_appellate', 'Federal court of appeals'), ('administrative', 'Administrative tribunal')], max_length=40)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('division', models.CharField(blank=True, max_length=160)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Other names this court is written under.')),
                ('verification', models.CharField(choices=[('verified', "Checked against the court's published rules"), ('unverified', "Starter profile, not checked against this court's rules")], default='unverified', max_length=30)),
                ('source', models.CharField(blank=True, help_text='The local rule these requirements come from.', max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('pleading_types', models.JSONField(blank=True, default=list)),
                ('formatting', models.JSONField(blank=True, default=dict)),
                ('required_elements', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('is_locally_edited', models.BooleanField(default=False, help_text='Set when this profile was edited here. Re-seeding from the content library skips it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'name'],
            },
        ),
    ]
