# Generated by Django 5.2.15 on 2026-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_courtprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRuleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('citation', models.CharField(help_text='How the rule is cited, e.g. R.C. 1923.04.', max_length=255)),
                ('rule_type', models.CharField(choices=[('statute', 'Statute'), ('civil_rule', 'Rule of procedure'), ('local_rule', 'Local rule'), ('doctrine', 'Common-law doctrine')], default='statute', max_length=40)),
                ('jurisdiction', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('citation_patterns', models.JSONField(blank=True, default=list, help_text='Regular expressions that mean this rule was cited.')),
                ('aliases', models.JSONField(blank=True, default=list, help_text="Phrases that invoke the rule without citing it, e.g. 'three-day notice'.")),
                ('elements', models.JSONField(blank=True, default=list, help_text="[{'id', 'label', 'requirement', 'patterns', 'needs_record_support', 'note'}]")),
                ('decision_table_key', models.SlugField(blank=True, help_text="A published decision table whose row already encodes this rule's requirements.", max_length=140)),
                ('decision_table_row', models.SlugField(blank=True, max_length=140)),
                ('verification', models.CharField(choices=[('verified', "Checked against the court's published rules"), ('unverified', "Starter profile, not checked against this court's rules")], default='unverified', max_length=30)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('is_locally_edited', models.BooleanField(default=False, help_text='Set when this profile was edited here. Re-seeding from the content library skips it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['jurisdiction', 'citation', 'name'],
            },
        ),
    ]
