# Generated by Django 5.2.15 on 2026-06-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RetrievedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_kind", models.CharField(max_length=80)),
                ("source_label", models.CharField(max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("snippet", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("citation", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("legalserver", "LegalServer"),
                            ("sharepoint", "SharePoint"),
                            ("rag", "RAG database"),
                            ("local_cases", "Local archived cases"),
                            ("user_resources", "User-specific resources"),
                        ],
                        max_length=80,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
    ]
