# Generated by Django 5.2.15 on 2026-08-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_user_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinanceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_slug', models.CharField(max_length=120)),
                ('target_key', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Clear this to park an override without deleting it.')),
                ('citation', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('act_file_number', models.CharField(blank=True, max_length=120)),
                ('enacted_as', models.CharField(blank=True, help_text='The chapter it was enacted under, if it has since moved.', max_length=255)),
                ('source_type', models.CharField(blank=True, choices=[('signed_ordinance', 'Signed ordinance'), ('council_packet', 'Council packet'), ('official_minutes', 'Official minutes'), ('codifier', 'Codifier'), ('secondary_reproduction', 'Secondary reproduction'), ('transcription', 'Hand transcription'), ('other', 'Other')], max_length=40)),
                ('legal_status', models.CharField(blank=True, choices=[('', 'Leave as generated'), ('in_force', 'In force'), ('repealed', 'Repealed'), ('expired', 'Expired'), ('unknown', 'Unknown')], max_length=20)),
                ('enacted_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('amended_date', models.DateField(blank=True, null=True)),
                ('repeal_date', models.DateField(blank=True, null=True)),
                ('preemption_status', models.CharField(blank=True, max_length=80)),
                ('preemption_note', models.TextField(blank=True)),
                ('controlling_case', models.CharField(blank=True, max_length=500)),
                ('court_treatment', models.TextField(blank=True)),
                ('preemption_confidence', models.CharField(blank=True, max_length=80)),
                ('verified', models.BooleanField(default=False, help_text="A person confirmed this authority's text against the publisher.")),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['municipality_slug', 'target_key'],
                'unique_together': {('municipality_slug', 'target_key')},
            },
        ),
        migrations.CreateModel(
            name='OrdinanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_slug', models.CharField(help_text='Scope slug, e.g. lakewood', max_length=120)),
                ('target_key', models.CharField(help_text='Target key within that municipality, e.g. pay-to-stay', max_length=120)),
                ('title', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('signed_ordinance', 'Signed ordinance'), ('council_packet', 'Council packet'), ('official_minutes', 'Official minutes'), ('codifier', 'Codifier'), ('secondary_reproduction', 'Secondary reproduction'), ('transcription', 'Hand transcription'), ('other', 'Other')], default='signed_ordinance', max_length=40)),
                ('url', models.URLField(blank=True, help_text='Publisher URL, when the document is hosted.', max_length=1000)),
                ('storage_key', models.TextField(blank=True, help_text='Set automatically when a file is uploaded.')),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('extract_start', models.CharField(blank=True, help_text='Text marking the start of the authority.', max_length=500)),
                ('extract_end', models.CharField(blank=True, help_text='Text marking where it ends.', max_length=500)),
                ('extract_pages', models.CharField(blank=True, help_text='PDF page range, e.g. 12-15.', max_length=40)),
                ('verified', models.BooleanField(default=False, help_text="A person compared this document against the publisher's copy. Nothing automated sets this.")),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_by', models.ForeignKey(blank=True, help_text='The document that replaced this one. Setting it does not delete anything.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='sources.ordinancedocument')),
            ],
            options={
                'ordering': ['municipality_slug', 'target_key', '-created_at'],
                'indexes': [models.Index(fields=['municipality_slug', 'target_key'], name='sources_ord_municip_cdb184_idx'), models.Index(fields=['status'], name='sources_ord_status_f2bcd3_idx'), models.Index(fields=['source_type'], name='sources_ord_source__a9ab39_idx')],
            },
        ),
    ]
