# Generated by Django 5.2.15 on 2026-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0008_ordinanceoverride_ordinancedocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordinancedocument",
            name="source_type",
            field=models.CharField(choices=[("signed_ordinance", "Signed ordinance"), ("council_packet", "Council packet"), ("official_minutes", "Official minutes"), ("official_publication", "Official publication (city record/journal)"), ("codifier", "Codifier"), ("secondary_reproduction", "Secondary reproduction"), ("transcription", "Hand transcription"), ("other", "Other")], default="signed_ordinance", max_length=40),
        ),
        migrations.AlterField(
            model_name="ordinanceoverride",
            name="source_type",
            field=models.CharField(blank=True, choices=[("signed_ordinance", "Signed ordinance"), ("council_packet", "Council packet"), ("official_minutes", "Official minutes"), ("official_publication", "Official publication (city record/journal)"), ("codifier", "Codifier"), ("secondary_reproduction", "Secondary reproduction"), ("transcription", "Hand transcription"), ("other", "Other")], max_length=40),
        ),
    ]
