# Generated by Django 5.2.15 on 2026-09-22 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_alter_ordinancedocument_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('treatise', 'Treatise or handbook'), ('case', 'Case decision'), ('ordinance', 'Local ordinance'), ('statute', 'Statute or regulation'), ('other', 'Other approved legal source')], max_length=30)),
                ('jurisdiction', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('source_locator', models.TextField(blank=True, help_text='Publisher URL, path, or other human-readable locator.')),
                ('source_system_id', models.CharField(blank=True, max_length=255)),
                ('refresh_command', models.CharField(blank=True, choices=[('', 'Manual upload'), ('ohio_revised_code', 'Ohio Revised Code'), ('local_ordinances', 'Local ordinances')], max_length=80)),
                ('court', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('municipality', models.CharField(blank=True, max_length=255)),
                ('appellate_district', models.CharField(blank=True, max_length=120)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('citation', models.CharField(blank=True, max_length=500)),
                ('publication_status', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(choices=[('draft', 'Draft / no published version'), ('published', 'Published'), ('retired', 'Retired'), ('failed', 'Latest import failed')], default='draft', max_length=20)),
                ('last_successful_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_managed_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'title'],
                'permissions': [('publish_managedsource', 'Can publish, retire, and roll back managed sources')],
            },
        ),
        migrations.CreateModel(
            name='ManagedSourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('pending_review', 'Pending metadata review'), ('published', 'Published'), ('superseded', 'Superseded'), ('failed', 'Failed validation or indexing')], default='uploaded', max_length=30)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('source_etag', models.CharField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('parser_version', models.CharField(max_length=120)),
                ('chunker_version', models.CharField(max_length=120)),
                ('raw_key', models.TextField()),
                ('validated_manifest_key', models.TextField(blank=True)),
                ('published_manifest_key', models.TextField(blank=True)),
                ('published_source_key', models.TextField(blank=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_source_versions', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='sources.managedsource')),
            ],
            options={
                'ordering': ['source', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ManagedSourceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sources.managedsource')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sources.managedsourceversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagedSourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(max_length=64)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.managedsourceversion')),
            ],
            options={
                'ordering': ['version', 'ordinal'],
            },
        ),
        migrations.AddField(
            model_name='managedsource',
            name='current_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_sources', to='sources.managedsourceversion'),
        ),
        migrations.AddConstraint(
            model_name='managedsourceversion',
            constraint=models.UniqueConstraint(fields=('source', 'number'), name='sources_unique_managed_version'),
        ),
        migrations.AddConstraint(
            model_name='managedsourceversion',
            constraint=models.UniqueConstraint(fields=('source', 'sha256'), name='sources_unique_managed_checksum'),
        ),
        migrations.AddConstraint(
            model_name='managedsourcechunk',
            constraint=models.UniqueConstraint(fields=('version', 'ordinal'), name='sources_unique_managed_chunk'),
        ),
    ]
