# Generated by Django 5.2.15 on 2026-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_managedsource_managedsourceversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedsourceversion',
            name='validation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
