# Generated by Django 5.2.15 on 2026-09-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0011_managedsourceversion_validation_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedsourceversion",
            name="source_provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
