# Generated by Django 5.2.15 on 2026-09-01 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drafting', '0012_alter_draftingsession_mode'),
        ('matters', '0004_legalserverdelivery_scope_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('brief_under_test', 'Brief under test'), ('case_record', 'Case record')], max_length=40)),
                ('source_type', models.CharField(choices=[('upload', 'Uploaded file'), ('draft_document', 'HaddenDraft document'), ('matter_document', 'Case file document')], max_length=40)),
                ('external_reference', models.JSONField(blank=True, default=dict, help_text="Stable pointer to a document that lives in another system: {'system', 'matterExternalId', 'documentId', 'title', 'url'}. The bytes stay there; only the reference is stored here.")),
                ('storage_key', models.CharField(blank=True, help_text='Key in apps.core.storage for an uploaded file, when one was retained.', max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_metadata', models.JSONField(blank=True, default=dict, help_text='Extractor name, page count, and the structural units found in the text.')),
                ('excluded', models.BooleanField(default=False, help_text='Excluded case materials stay listed but are not read by the next run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_documents', to='drafting.draftdocument')),
            ],
            options={
                'ordering': ['role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GymRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='What the brief was when this run read it: component version ids for a native draft, a text checksum otherwise. A rerun diffs against this.')),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('research_trace', models.JSONField(blank=True, default=list, help_text='Adversarial queries run, the sources searched, and the augmentation rounds each took.')),
                ('materials', models.JSONField(blank=True, default=list, help_text='Every document this run actually read, and why it was chosen.')),
                ('stage_trace', models.JSONField(blank=True, default=list)),
                ('comparison', models.JSONField(blank=True, default=dict, help_text='How this run relates to the one before it: which challenges recurred, which are new, and which stopped being raised once the brief changed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('summary', models.TextField(blank=True, help_text='Narrative orientation written once from the stored challenges and reused by every artifact.')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='argument_gym.gymdocument')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_runs', to=settings.AUTH_USER_MODEL)),
                ('previous_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='argument_gym.gymrun')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GymChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('legal_authority', 'Legal authority'), ('factual_support', 'Factual support'), ('record_conflict', 'Record conflict'), ('procedural', 'Procedural'), ('remedy_scope', 'Scope of relief'), ('framing', 'Framing'), ('missing_element', 'Missing element')], default='legal_authority', max_length=40)),
                ('fingerprint', models.CharField(blank=True, help_text='Stable hash of target and argument, so a rerun can tell a repeat from a new challenge.', max_length=64)),
                ('target', models.JSONField(blank=True, default=dict, help_text="Where in the brief this lands: {'unitId', 'section', 'paragraph', 'page', 'excerpt', 'blockKey'}.")),
                ('opponent_argument', models.TextField()),
                ('why_it_matters', models.TextField(blank=True)),
                ('brief_currently_says', models.TextField(blank=True)),
                ('legal_sources', models.JSONField(blank=True, default=list)),
                ('record_sources', models.JSONField(blank=True, default=list)),
                ('judge_assessment', models.TextField(blank=True)),
                ('judge_verdict', models.CharField(blank=True, max_length=60)),
                ('coaching_recommendation', models.TextField(blank=True)),
                ('suggested_response', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('importance', models.PositiveSmallIntegerField(default=50)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('research_coverage', models.JSONField(blank=True, default=dict)),
                ('disposition', models.CharField(choices=[('open', 'Open'), ('addressed', 'Addressed'), ('dismissed', 'Dismissed')], default='open', max_length=30)),
                ('disposition_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carried_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='argument_gym.gymchallenge')),
                ('resulting_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_challenges', to='drafting.draftoperation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='argument_gym.gymrun')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GymWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(blank=True, help_text='Set when the brief is tested against a real case file. Access is resolved through this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_workspaces', to='matters.matter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='gymrun',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='argument_gym.gymworkspace'),
        ),
        migrations.AddField(
            model_name='gymdocument',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='argument_gym.gymworkspace'),
        ),
    ]
