# Generated by Django 5.2.15 on 2026-09-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_gym', '0001_initial'),
        ('rules', '0003_courtprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdocument',
            name='page_range',
            field=models.JSONField(blank=True, default=dict, help_text="{'start', 'end'} when this document is one span of pages split out of a larger upload."),
        ),
        migrations.AddField(
            model_name='gymdocument',
            name='pleading_type',
            field=models.CharField(blank=True, help_text="What kind of paper this is, which decides which of a court's rules apply to it.", max_length=60),
        ),
        migrations.AddField(
            model_name='gymdocument',
            name='split_from',
            field=models.ForeignKey(blank=True, help_text='The upload this was separated out of, for an exhibit detached from a filed brief.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_parts', to='argument_gym.gymdocument'),
        ),
        migrations.AddField(
            model_name='gymrun',
            name='assessment',
            field=models.TextField(blank=True, help_text='One paragraph at the top of the report: how persuasive the brief is and what most needs fixing.'),
        ),
        migrations.AddField(
            model_name='gymrun',
            name='assessment_verdict',
            field=models.CharField(blank=True, help_text='The headline judgment the paragraph expands on. A characterization, never a score.', max_length=60),
        ),
        migrations.AddField(
            model_name='gymrun',
            name='compliance',
            field=models.JSONField(blank=True, default=dict, help_text='Deterministic filing-format findings, and which properties could not be measured.'),
        ),
        migrations.AddField(
            model_name='gymrun',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_runs', to='rules.courtprofile'),
        ),
        migrations.AddField(
            model_name='gymrun',
            name='court_detection',
            field=models.JSONField(blank=True, default=dict, help_text='How the court was arrived at: detected and on what evidence, or set by hand.'),
        ),
        migrations.AddField(
            model_name='gymworkspace',
            name='court',
            field=models.ForeignKey(blank=True, help_text='Whose filing-format rules apply. Detected or chosen, according to court_rule_mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_workspaces', to='rules.courtprofile'),
        ),
        migrations.AddField(
            model_name='gymworkspace',
            name='court_rule_mode',
            field=models.CharField(choices=[('auto', "Apply the detected court's rules"), ('manual', "Apply a chosen court's rules"), ('off', 'Skip filing-format rules')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='gymworkspace',
            name='jurisdiction_detail',
            field=models.JSONField(blank=True, default=dict, help_text="Jurisdiction set by hand: {'state', 'county', 'municipality', 'division', 'courtType'}. Municipality is left out for an appellate division, where it means nothing."),
        ),
        migrations.AddField(
            model_name='gymworkspace',
            name='jurisdiction_mode',
            field=models.CharField(choices=[('auto', 'Detect automatically'), ('manual', 'Set by hand')], default='auto', max_length=20),
        ),
    ]
