# Generated by Django 5.2.15 on 2026-09-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_gym', '0003_gymrun_check_results_gymrun_checklist_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymdocument',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Uploaded file'), ('draft_document', 'Draft from this tool'), ('matter_document', 'Case file document')], max_length=40),
        ),
    ]
