# Generated by Django 5.2.15 on 2026-08-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jurisdiction_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='bar_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='fax',
            field=models.CharField(blank=True, help_text='Leave empty to hide the fax line on the letterhead.', max_length=80),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='office_name',
            field=models.CharField(blank=True, help_text='Which office the advocate works from, e.g. "Cleveland" or "Elyria".', max_length=255),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='title',
            field=models.CharField(blank=True, help_text='Job title as it appears on letterhead, e.g. "Staff Attorney".', max_length=255),
        ),
    ]
