# Generated by Django 5.2.15 on 2026-08-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authorprofile_bar_number_authorprofile_fax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='letter_filename_pattern',
            field=models.CharField(blank=True, help_text='Download name for advice letters. Placeholders: {date}, {client} (surname-first), {sections} (up to three), {case}, {kind}. Empty uses 2026-08-02-garcia-robert-advice-letter-security-deposit.', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='letter_filename_section_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many section names to include before the filename gets unwieldy.'),
        ),
    ]
