# Generated by Django 5.2.15 on 2026-06-24 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255)),
                ('workflow_run_id', models.CharField(blank=True, max_length=255)),
                ('issue_id', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('issue_type', models.CharField(choices=[('defense', 'Defense'), ('counterclaim', 'Counterclaim'), ('denial', 'Denial'), ('review_gate', 'Review gate'), ('missing_fact', 'Missing fact')], max_length=50)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inserted', 'Inserted into draft')], default='candidate', max_length=50)),
                ('source_table_key', models.SlugField()),
                ('source_table_version', models.PositiveIntegerField()),
                ('source_row_id', models.SlugField()),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('supporting_facts', models.JSONField(blank=True, default=list)),
                ('missing_facts', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['case_id', 'created_at', 'id'],
                'indexes': [models.Index(fields=['case_id', 'status'], name='issues_cand_case_id_284973_idx'), models.Index(fields=['source_table_key', 'source_table_version'], name='issues_cand_source__023734_idx')],
            },
        ),
    ]
