# Generated by Django 5.2.15 on 2026-06-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("templates_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("research", "Research"),
                            ("draft_from_scratch", "Draft from scratch"),
                            ("draft_from_template", "Draft from template"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("case", "Case"),
                            ("facts", "Facts"),
                            ("template", "Template"),
                            ("law", "Law and Sources"),
                            ("draft", "Draft"),
                            ("export", "Export"),
                        ],
                        default="case",
                        max_length=80,
                    ),
                ),
                ("selected_fact_ids", models.JSONField(blank=True, default=list)),
                ("selected_source_results", models.JSONField(blank=True, default=list)),
                ("selected_block_keys", models.JSONField(blank=True, default=list)),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafting_sessions",
                        to="matters.matter",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafting_sessions",
                        to="templates_app.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DraftDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sections", models.JSONField(default=list)),
                ("plain_text", models.TextField()),
                ("editor_state", models.JSONField(blank=True, default=dict)),
                ("validation_flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="drafting.draftingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
