# Generated by Django 5.2.15 on 2026-06-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafting", "0003_draftingsession_author_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("setup", "Choose document"),
                    ("facts_review", "Review facts"),
                    ("support_review", "Review support"),
                    ("law_review", "Review legal issues"),
                    ("outline_review", "Approve outline"),
                    ("draft_review", "Review draft"),
                    ("validation", "Validation"),
                    ("export", "Export"),
                ],
                default="setup",
                max_length=80,
            ),
        ),
    ]
