# Generated by Django 5.2.15 on 2026-08-01 14:18

import django.db.models.deletion
from django.db import migrations, models


def backfill_draft_template(apps, _schema_editor):
    """Recover each draft's template from editor_state, falling back to its session."""
    DraftDocument = apps.get_model("drafting", "DraftDocument")
    DocumentTemplate = apps.get_model("templates_app", "DocumentTemplate")

    ids_by_slug = dict(DocumentTemplate.objects.values_list("slug", "id"))
    known_ids = set(ids_by_slug.values())

    updated = []
    for draft in DraftDocument.objects.select_related("session").all():
        editor_state = draft.editor_state or {}
        template_id = editor_state.get("templateId")
        if template_id not in known_ids:
            template_id = ids_by_slug.get(editor_state.get("templateSlug"))
        if template_id is None:
            template_id = draft.session.template_id
        if template_id is not None:
            draft.template_id = template_id
            updated.append(draft)
    if updated:
        DraftDocument.objects.bulk_update(updated, ["template"])


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0006_drafting_plan_fields'),
        ('templates_app', '0006_template_goal_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftdocument',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this document was generated from. A session can produce several documents from different templates, so export renders from this, not the session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='templates_app.documenttemplate'),
        ),
        migrations.RunPython(backfill_draft_template, migrations.RunPython.noop),
    ]
