# Generated by Django 5.2.15 on 2026-08-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0007_draftdocument_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(help_text='Identity of this component within the document, normally the template block key.', max_length=160)),
                ('component_type', models.CharField(blank=True, max_length=80)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('removed_at', models.DateTimeField(blank=True, help_text='Set when the component left the document. History is kept rather than deleted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='drafting.draftdocument')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drafting.documentcomponent')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('document', 'stable_key')},
            },
        ),
        migrations.CreateModel(
            name='ComponentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True)),
                ('structured_content', models.JSONField(blank=True, default=dict, help_text='Section fields other than key, label, and body, such as sources and formatting.')),
                ('origin', models.CharField(choices=[('template', 'Template'), ('ai', 'AI generation'), ('human', 'Human edit'), ('validation_repair', 'Validation repair'), ('rollback', 'Rollback')], default='template', max_length=40)),
                ('instruction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drafting.documentcomponent')),
            ],
            options={
                'ordering': ['component_id', 'sequence'],
                'unique_together': {('component', 'sequence')},
            },
        ),
    ]
