# Generated by Django 5.2.15 on 2026-08-02 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0008_documentcomponent_componentversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('replace_component', 'Replace component'), ('insert_component', 'Insert component'), ('delete_component', 'Delete component'), ('move_component', 'Move component'), ('revert_component', 'Revert component to an earlier version')], max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='proposed', max_length=30)),
                ('origin', models.CharField(choices=[('template', 'Template'), ('ai', 'AI generation'), ('human', 'Human edit'), ('validation_repair', 'Validation repair'), ('rollback', 'Rollback')], default='human', max_length=40)),
                ('decision_note', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='drafting.draftdocument')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_operations', to=settings.AUTH_USER_MODEL)),
                ('target_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='drafting.documentcomponent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
