# Generated by Django 5.2.15 on 2026-08-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0009_draftoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(help_text='Stable identifier of the source within its system.', max_length=255)),
                ('source_kind', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('record_evidence', 'Record evidence'), ('legal_authority', 'Legal authority'), ('procedural_rule', 'Procedural rule'), ('example_language', 'Example language'), ('background_reference', 'Background reference')], max_length=40)),
                ('support_type', models.CharField(choices=[('direct', 'Direct'), ('inference', 'Inference'), ('background', 'Background'), ('style_only', 'Style only')], max_length=40)),
                ('label', models.CharField(blank=True, max_length=500)),
                ('citation', models.CharField(blank=True, max_length=500)),
                ('locator', models.JSONField(blank=True, default=dict, help_text='Where in the source the support is, such as a fact id, URL, or excerpt index.')),
                ('excerpt', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False, help_text='Set once the locator and quoted text have been checked against the source.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='drafting.componentversion')),
            ],
            options={
                'ordering': ['component_version_id', 'id'],
            },
        ),
    ]
