# Generated by Django 5.2.15 on 2026-08-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0010_sourcebinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('cites', 'Cites'), ('authenticates_exhibit', 'Authenticates exhibit'), ('implements_relief', 'Implements relief'), ('incorporates', 'Incorporates'), ('depends_on', 'Depends on')], max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='drafting.draftdocument')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='drafting.draftdocument')),
            ],
            options={
                'ordering': ['source_document_id', 'relationship_type'],
                'unique_together': {('source_document', 'target_document', 'relationship_type')},
            },
        ),
    ]
