# Generated by Django 5.2.15 on 2026-08-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafting", "0011_packagerelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftingsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("research", "Research"),
                    ("draft_from_scratch", "Draft from scratch"),
                    ("draft_from_template", "Draft from template"),
                    ("advice_letter", "Client advice letter"),
                ],
                max_length=80,
            ),
        ),
    ]
