# Generated by Django 5.2.15 on 2026-09-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0013_draft_generation_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draftingsession',
            name='fill_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='draftingsession',
            name='mode',
            field=models.CharField(choices=[('template_fill', 'Fill template — no AI'), ('research', 'Research'), ('draft_from_scratch', 'Draft from scratch'), ('draft_from_template', 'Draft from template'), ('advice_letter', 'Client advice letter')], max_length=80),
        ),
        migrations.CreateModel(
            name='TemplateFillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('prepare', 'Prepare'), ('export', 'Export')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_jobs', to='drafting.draftingsession')),
            ],
        ),
    ]
