# Generated by Django 5.2.15 on 2026-09-25 21:07

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def retire_duplicate_active_jobs(apps, schema_editor):
    """Before one active generation per session is enforced, keep the newest.

    An older pending or running job for a session that has a newer one is a
    leftover from before this guard; it is marked failed with a reason rather
    than deleted, so its record survives.
    """
    Job = apps.get_model("drafting", "DraftGenerationJob")
    seen = set()
    for job in Job.objects.filter(status__in=["pending", "running"]).order_by("session_id", "-created_at", "-id"):
        if job.session_id in seen:
            job.status = "failed"
            job.error = "Superseded by a newer generation for this session."
            job.completed_at = timezone.now()
            job.save(update_fields=["status", "error", "completed_at"])
        seen.add(job.session_id)


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0014_draftingsession_fill_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draftdocument',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draftdocument',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftdocument',
            name='validated_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftdocument',
            name='validation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='draftgenerationjob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='draftgenerationjob',
            name='input_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='draftgenerationjob',
            name='input_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftingsession',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draftingsession',
            name='workflow_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(retire_duplicate_active_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='draftgenerationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('session',), name='one_active_generation_per_session'),
        ),
        migrations.AddConstraint(
            model_name='draftgenerationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('session', 'idempotency_key'), name='unique_generation_idempotency_key'),
        ),
    ]
