# Generated by Django 5.2.15 on 2026-09-26 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0015_editing_revisions_and_generation_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpposingFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('matter_document', 'Case file document'), ('upload', 'Uploaded file')], max_length=40)),
                ('filing_kind', models.CharField(blank=True, help_text="What the filing is, from the template's list: complaint, brief_in_opposition, ...", max_length=60)),
                ('external_reference', models.JSONField(blank=True, default=dict, help_text="For a case file document: {'system', 'matterExternalId', 'documentId', 'title', 'url'}. The bytes stay in that system.")),
                ('storage_key', models.CharField(blank=True, help_text='Key in the raw/ area of apps.core.storage, for an uploaded copy.', max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, help_text='How the draft names the filing, e.g. "Plaintiff\'s Brief in Opposition".', max_length=500)),
                ('filed_on', models.DateField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True, help_text="The filing's own text, for an upload. A case file document is read when drafting.")),
                ('extraction_metadata', models.JSONField(blank=True, default=dict, help_text='Extractor, page count, the exhibits separated from the filing, and whether text was capped.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opposing_filing', to='drafting.draftingsession')),
            ],
        ),
    ]
