# Generated by Django 5.2.15 on 2026-06-24 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255)),
                ('field_path', models.CharField(max_length=255)),
                ('value', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('llm', 'LLM'), ('legalserver', 'LegalServer'), ('user', 'User'), ('parser', 'Parser'), ('deterministic', 'Deterministic')], default='llm', max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], default='unreviewed', max_length=50)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['case_id', 'field_path', 'id'],
                'indexes': [models.Index(fields=['case_id', 'field_path'], name='facts_extra_case_id_98dbac_idx'), models.Index(fields=['case_id', 'review_status'], name='facts_extra_case_id_1ecbbd_idx')],
            },
        ),
    ]
