"""Publish the generated local-ordinance corpus from the raw area to the published area.

The corpus is machine-written -- manifests, sections, and retrieval chunks
regenerated by ``scripts/ingest_local_ordinances.py`` -- so it is data rather
than source and is not committed. An operator uploads it into
``raw/ordinances/``, and this is the moment it becomes visible to the
application, under ``published/content/ordinances/`` where
``PUBLISHED_CONTENT_LIBRARY_DIR`` points.

Separating the two areas is what makes a slow upload safe: several thousand
small markdown files can accumulate under ``raw/`` for as long as the transfer
takes without a running replica ever reading a half-written corpus.
"""
from django.core.management.base import BaseCommand

from apps.core.storage import PUBLISHED, RAW, copy_area, get_document_storage


# The same key in both areas, so publishing is a copy rather than a rename.
# "content/ordinances" rather than "ordinances" keeps the generated corpus clear
# of published/ordinances/, which holds the documents an operator attaches to an
# authority through the admin.
PREFIX = "content/ordinances"


class Command(BaseCommand):
    help = "Copy the generated local-ordinance corpus from the raw storage area to the published area."

    def add_arguments(self, parser):
        parser.add_argument(
            "--overwrite",
            action="store_true",
            help="Re-copy objects that already exist in the published area.",
        )
        parser.add_argument(
            "--verbose-keys",
            action="store_true",
            help="Print every key as it is copied.",
        )

    def handle(self, *args, **options):
        raw = get_document_storage(RAW)
        published = get_document_storage(PUBLISHED)

        self.stdout.write(f"Publishing {PREFIX}/ from {RAW} to {PUBLISHED} ({raw.backend_name})")
        progress = (lambda key: self.stdout.write(f"  {key}")) if options["verbose_keys"] else None
        copied, skipped = copy_area(
            raw,
            published,
            prefix=PREFIX,
            skip_existing=not options["overwrite"],
            progress=progress,
        )

        # An empty raw area is the normal state for a deployment whose ordinance
        # corpus has not been uploaded yet. Say so plainly: reporting success
        # over a no-op would read as "the corpus is in place".
        if copied == 0 and skipped == 0:
            self.stdout.write(
                f"Nothing to publish: {RAW}/{PREFIX}/ is empty. "
                f"Local law will be missing until it is uploaded."
            )
            return
        self.stdout.write(self.style.SUCCESS(f"Published {copied} object(s), skipped {skipped} already present."))
