# Generated manually for the first caselaw ingestion schema.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseLawDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("short_title", models.CharField(blank=True, max_length=500)),
                ("normalized_title", models.CharField(blank=True, max_length=500)),
                ("docket_number", models.CharField(blank=True, max_length=255)),
                ("case_number", models.CharField(blank=True, max_length=255)),
                ("external_source_id", models.CharField(blank=True, max_length=255)),
                ("court", models.CharField(blank=True, max_length=255)),
                ("court_division", models.CharField(blank=True, max_length=255)),
                ("county", models.CharField(blank=True, max_length=255)),
                ("jurisdiction", models.CharField(blank=True, max_length=120)),
                ("judge", models.CharField(blank=True, max_length=255)),
                ("magistrate", models.CharField(blank=True, max_length=255)),
                ("parties", models.JSONField(blank=True, default=list)),
                ("party_roles", models.JSONField(blank=True, default=list)),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("entry_date", models.DateField(blank=True, null=True)),
                ("filed_date", models.DateField(blank=True, null=True)),
                ("hearing_date", models.DateField(blank=True, null=True)),
                ("service_date", models.DateField(blank=True, null=True)),
                ("finality_date", models.DateField(blank=True, null=True)),
                ("appeal_deadline", models.DateField(blank=True, null=True)),
                ("appeal_filed_date", models.DateField(blank=True, null=True)),
                ("vacated_date", models.DateField(blank=True, null=True)),
                ("reversed_date", models.DateField(blank=True, null=True)),
                ("superseded_date", models.DateField(blank=True, null=True)),
                ("publication_status", models.CharField(default="unpublished", max_length=80)),
                ("precedential_status", models.CharField(blank=True, max_length=120)),
                ("authority_level", models.CharField(blank=True, max_length=120)),
                ("court_level", models.CharField(blank=True, max_length=120)),
                ("is_unpublished", models.BooleanField(default=True)),
                ("is_trial_court", models.BooleanField(default=False)),
                ("is_administrative", models.BooleanField(default=False)),
                ("is_persuasive_only", models.BooleanField(default=True)),
                ("citation_string", models.CharField(blank=True, max_length=500)),
                ("parallel_citations", models.JSONField(blank=True, default=list)),
                ("westlaw_lexis_citation_if_any", models.CharField(blank=True, max_length=500)),
                ("case_type", models.CharField(blank=True, max_length=255)),
                ("claim_type", models.CharField(blank=True, max_length=255)),
                ("motion_type", models.CharField(blank=True, max_length=255)),
                ("procedural_stage", models.CharField(blank=True, max_length=255)),
                ("posture", models.TextField(blank=True)),
                ("appeal_status", models.CharField(blank=True, max_length=120)),
                ("tenant_landlord_role", models.CharField(blank=True, max_length=120)),
                ("subsidy_program", models.CharField(blank=True, max_length=255)),
                ("housing_type", models.CharField(blank=True, max_length=255)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("holdings", models.JSONField(blank=True, default=list)),
                ("rules_applied", models.JSONField(blank=True, default=list)),
                ("statutes_cited", models.JSONField(blank=True, default=list)),
                ("regulations_cited", models.JSONField(blank=True, default=list)),
                ("cases_cited", models.JSONField(blank=True, default=list)),
                ("key_facts", models.TextField(blank=True)),
                ("outcome", models.TextField(blank=True)),
                ("relief_granted", models.TextField(blank=True)),
                ("relief_denied", models.TextField(blank=True)),
                ("disposition", models.TextField(blank=True)),
                ("treatment_status", models.CharField(default="unchecked", max_length=80)),
                ("treatment_notes", models.TextField(blank=True)),
                ("negative_treatment_type", models.CharField(blank=True, max_length=120)),
                ("negative_treatment_source", models.TextField(blank=True)),
                ("related_appeal_case", models.TextField(blank=True)),
                ("later_history", models.TextField(blank=True)),
                ("overruled_by", models.TextField(blank=True)),
                ("distinguished_by", models.JSONField(blank=True, default=list)),
                ("followed_by", models.JSONField(blank=True, default=list)),
                ("cited_by", models.JSONField(blank=True, default=list)),
                ("last_treatment_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_currentness_reviewed_by", models.CharField(blank=True, max_length=255)),
                ("last_currentness_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("original_filename", models.CharField(blank=True, max_length=500)),
                ("source_sha256", models.CharField(max_length=64, unique=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("has_embedded_text", models.BooleanField(default=False)),
                ("has_ocr_layer", models.BooleanField(default=False)),
                ("metadata_source", models.CharField(default="unverified_json", max_length=80)),
                ("metadata_verified", models.BooleanField(default=False)),
                ("approved_for_search", models.BooleanField(default=True)),
                ("approved_for_drafting", models.BooleanField(default=False)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-decision_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="CaseLawImportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_path", models.TextField()),
                ("storage_backend", models.CharField(max_length=80)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="running", max_length=40)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("total_cases", models.PositiveIntegerField(default=0)),
                ("imported_cases", models.PositiveIntegerField(default=0)),
                ("skipped_cases", models.PositiveIntegerField(default=0)),
                ("failed_cases", models.PositiveIntegerField(default=0)),
                ("report", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseLawArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("artifact_type", models.CharField(max_length=80)),
                ("original_filename", models.CharField(blank=True, max_length=500)),
                ("storage_backend", models.CharField(max_length=80)),
                ("storage_key", models.TextField()),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="caselaw.caselawdecision")),
            ],
            options={
                "ordering": ["artifact_type", "original_filename"],
                "unique_together": {("decision", "artifact_type", "storage_key")},
            },
        ),
        migrations.CreateModel(
            name="CaseLawChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_type", models.CharField(default="body", max_length=80)),
                ("page_start", models.PositiveIntegerField(default=1)),
                ("page_end", models.PositiveIntegerField(default=1)),
                ("text", models.TextField()),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("ocr_confidence_min", models.FloatField(blank=True, null=True)),
                ("has_handwriting", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="caselaw.caselawdecision")),
            ],
            options={
                "ordering": ["decision_id", "ordinal"],
                "unique_together": {("decision", "chunk_type", "ordinal")},
            },
        ),
        migrations.CreateModel(
            name="CaseLawPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("page_number", models.PositiveIntegerField()),
                ("text", models.TextField(blank=True)),
                ("ocr_confidence_avg", models.FloatField(blank=True, null=True)),
                ("ocr_confidence_min", models.FloatField(blank=True, null=True)),
                ("is_handwritten", models.BooleanField(default=False)),
                ("needs_review", models.BooleanField(default=False)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="caselaw.caselawdecision")),
            ],
            options={
                "ordering": ["decision_id", "page_number"],
                "unique_together": {("decision", "page_number")},
            },
        ),
        migrations.CreateModel(
            name="CaseLawSearchDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_type", models.CharField(max_length=80)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("search_text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("chunk", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="caselaw.caselawchunk")),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="search_documents", to="caselaw.caselawdecision")),
            ],
            options={
                "ordering": ["decision_id", "document_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="CaseLawSimilarityEdge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relation_type", models.CharField(default="similar", max_length=80)),
                ("score", models.FloatField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="similar_from", to="caselaw.caselawdecision")),
                ("to_decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="similar_to", to="caselaw.caselawdecision")),
            ],
            options={
                "ordering": ["-score"],
                "unique_together": {("from_decision", "to_decision", "relation_type")},
            },
        ),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["decision_date"], name="caselaw_cas_decisio_f0e849_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["entry_date"], name="caselaw_cas_entry_d_de54ab_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["court"], name="caselaw_cas_court_b29d09_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["county"], name="caselaw_cas_county_c8a6c1_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["jurisdiction"], name="caselaw_cas_jurisdi_63f925_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["judge"], name="caselaw_cas_judge_0d9549_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["publication_status"], name="caselaw_cas_public_39f994_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["authority_level"], name="caselaw_cas_authori_78e204_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["treatment_status"], name="caselaw_cas_treatme_34a0b0_idx")),
        migrations.AddIndex(model_name="caselawdecision", index=models.Index(fields=["approved_for_search"], name="caselaw_cas_approve_7d42d7_idx")),
        migrations.AddIndex(model_name="caselawsearchdocument", index=models.Index(fields=["decision", "document_type"], name="caselaw_cas_decisio_5f7595_idx")),
        migrations.AddIndex(model_name="caselawsearchdocument", index=models.Index(fields=["document_type"], name="caselaw_cas_documen_9a60ec_idx")),
    ]
