# Generated by Django 5.2.15 on 2026-07-08.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("caselaw", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_decisio_ea2bf0_idx",
            old_name="caselaw_cas_decisio_f0e849_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_entry_d_c26c51_idx",
            old_name="caselaw_cas_entry_d_de54ab_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_court_8942fc_idx",
            old_name="caselaw_cas_court_b29d09_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_county_780c66_idx",
            old_name="caselaw_cas_county_c8a6c1_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_jurisdi_2839ab_idx",
            old_name="caselaw_cas_jurisdi_63f925_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_judge_ad757c_idx",
            old_name="caselaw_cas_judge_0d9549_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_publica_45070e_idx",
            old_name="caselaw_cas_public_39f994_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_authori_c9c28d_idx",
            old_name="caselaw_cas_authori_78e204_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_treatme_6f8aa6_idx",
            old_name="caselaw_cas_treatme_34a0b0_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawdecision",
            new_name="caselaw_cas_approve_9d420e_idx",
            old_name="caselaw_cas_approve_7d42d7_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawsearchdocument",
            new_name="caselaw_cas_decisio_730af0_idx",
            old_name="caselaw_cas_decisio_5f7595_idx",
        ),
        migrations.RenameIndex(
            model_name="caselawsearchdocument",
            new_name="caselaw_cas_documen_24090d_idx",
            old_name="caselaw_cas_documen_9a60ec_idx",
        ),
    ]
