# Generated by Django 5.2.15 on 2026-07-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselaw', '0002_rename_caselaw_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselawdecision',
            name='search_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
