# Generated by Django 5.2.15 on 2026-08-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caselaw", "0003_caselawdecision_search_keywords"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseLawDateProvenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=40)),
                ("value", models.DateField(blank=True, null=True)),
                ("raw_value", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("metadata_sidecar", "Metadata sidecar"),
                            ("ocr_text", "OCR text"),
                        ],
                        default="metadata_sidecar",
                        max_length=40,
                    ),
                ),
                ("source_key", models.TextField(blank=True)),
                ("source_sha256", models.CharField(blank=True, max_length=64)),
                ("corroborated", models.BooleanField(default=False)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("matched_text", models.CharField(blank=True, max_length=255)),
                ("match_kind", models.CharField(blank=True, max_length=40)),
                ("context_label", models.CharField(blank=True, max_length=40)),
                ("snippet", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_provenance",
                        to="caselaw.caselawdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["decision_id", "field"],
                "indexes": [
                    models.Index(fields=["field"], name="caselaw_cas_field_7f808b_idx"),
                    models.Index(
                        fields=["corroborated"], name="caselaw_cas_corrobo_596d4d_idx"
                    ),
                ],
                "unique_together": {("decision", "field")},
            },
        ),
    ]
