# Generated by Django 5.2.15 on 2026-06-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("answer_counterclaims", "Answer and Counterclaims"),
                            ("motion", "Motion"),
                            ("brief", "Brief"),
                            ("hearing_statement", "Hearing Statement"),
                            ("shell", "Drafting shell"),
                        ],
                        max_length=80,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("jurisdiction", models.CharField(blank=True, max_length=255)),
                (
                    "source_label",
                    models.CharField(default="Internal template", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_from_example", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TemplateBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=120)),
                ("label", models.CharField(max_length=255)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("caption", "Caption"),
                            ("facts", "Facts"),
                            ("argument", "Argument"),
                            ("relief", "Prayer for Relief"),
                            ("signature", "Signature"),
                            ("certificate", "Certificate of Service"),
                            ("optional_clause", "Optional Clause"),
                        ],
                        max_length=80,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("body", models.TextField()),
                ("required", models.BooleanField(default=True)),
                ("ai_fill_mode", models.CharField(default="none", max_length=80)),
                ("selection_rule", models.JSONField(blank=True, default=dict)),
                ("supporting_sources", models.JSONField(blank=True, default=list)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="templates_app.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("template", "key")},
            },
        ),
    ]
