# Generated by Django 5.2.15 on 2026-08-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0006_template_goal_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblock',
            name='ai_instructions',
            field=models.JSONField(blank=True, default=list, help_text='Drafting directions the template author wrote into this block.'),
        ),
        migrations.AddField(
            model_name='templateblock',
            name='ai_latitude',
            field=models.CharField(choices=[('locked', 'Locked - render the maintained wording verbatim'), ('guided', 'Guided - maintained wording, rewritable on review'), ('generate', 'Generate - the model writes this block')], default='locked', help_text='How much of this block the model may write. Locked blocks render the maintained wording verbatim; guided blocks render it but accept a reviewed rewrite; generate blocks are written from the instructions.', max_length=20),
        ),
    ]
