# Generated by Django 5.2.15 on 2026-08-02 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0007_templateblock_ai_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letterhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('docx', models.FileField(blank=True, help_text='A .docx/.dotx whose advocate contact lines are Jinja variables. Upload an ordinary letterhead and the admin will parameterize it.', upload_to='letterheads/', validators=[django.core.validators.FileExtensionValidator(['docx', 'dotx'])])),
                ('content_path', models.CharField(blank=True, help_text='Provider-relative path when the letterhead ships in the content library.', max_length=500)),
                ('source_kind', models.CharField(choices=[('database', 'Uploaded through admin'), ('content_library', 'Content library')], default='database', max_length=40)),
                ('is_default', models.BooleanField(default=False, help_text="Used for letters when the advocate's office does not name its own.")),
                ('is_active', models.BooleanField(default=True)),
                ('is_placeholder', models.BooleanField(default=False, help_text='A neutral stand-in shipped so a fresh install can draft letters.')),
                ('variables', models.JSONField(blank=True, default=list)),
                ('preparation_report', models.JSONField(blank=True, default=dict, help_text='What the parameterizer replaced, kept for auditing an upload.')),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'title'],
            },
        ),
    ]
