# Generated by Django 5.2.15 on 2026-08-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0008_letterhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='kind',
            field=models.CharField(choices=[('answer_counterclaims', 'Answer and Counterclaims'), ('motion', 'Motion'), ('brief', 'Brief'), ('hearing_statement', 'Hearing Statement'), ('shell', 'Drafting shell'), ('worksheet', 'Spreadsheet exhibit')], max_length=80),
        ),
    ]
