# Generated by Django 5.2.15 on 2026-08-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0009_alter_documenttemplate_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceLetterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('intro', 'Opening'), ('body', 'Advice section'), ('closing', 'Closing')], default='body', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('letter_type', models.CharField(choices=[('brief_advice', 'Brief advice'), ('full_rep', 'Full representation action item')], default='brief_advice', max_length=40)),
                ('region', models.CharField(blank=True, help_text='"CLE", "NEO", or blank when the section applies anywhere.', max_length=20)),
                ('cleveland_specific', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ready', 'Ready to send'), ('needs_review', 'Needs review - had tracked changes or comments'), ('ai_drafted', 'Drafted by AI - attorney review required'), ('stub', 'Stub - not enough content to send')], default='ready', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('content_path', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('slots', models.JSONField(blank=True, default=list, help_text='Authoring notes pointing at another section, e.g. [Insert next defense].')),
                ('variants', models.JSONField(blank=True, default=list)),
                ('selection_hints', models.JSONField(blank=True, default=dict, help_text='Triggers, requirements, and conflicts used to rank this section.')),
                ('readability', models.JSONField(blank=True, default=dict)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('source_kind', models.CharField(default='content_library', max_length=40)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic', 'order', 'title'],
            },
        ),
    ]
