# Generated by Django 5.2.15 on 2026-08-02 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0010_advicelettersection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advicelettersection',
            name='copyedit',
            field=models.JSONField(blank=True, default=dict, help_text='What the copy-edit pass fixed, and what it left for a human to read.'),
        ),
        migrations.AddField(
            model_name='advicelettersection',
            name='is_locally_edited',
            field=models.BooleanField(default=False, help_text="Edited here rather than in the content library. Re-ingesting will not overwrite this section's text, status, or review state."),
        ),
        migrations.AddField(
            model_name='advicelettersection',
            name='needs_attorney_review',
            field=models.BooleanField(default=False, help_text='Set on anything that was not ready as maintained: tracked changes accepted here, text drafted here, or a passage a merge left doubtful.'),
        ),
        migrations.AddField(
            model_name='advicelettersection',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advicelettersection',
            name='review_reason',
            field=models.CharField(blank=True, help_text='Why this needs checking, in one line.', max_length=255),
        ),
        migrations.AddField(
            model_name='advicelettersection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advicelettersection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_advice_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
