# Generated by Django 5.2.15 on 2026-09-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationsettings_letter_filename_pattern_and_more'),
        ('matters', '0004_legalserverdelivery_scope_key_and_more'),
        ('templates_app', '0012_advicelettersection_editor_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FillTemplateUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('raw_key', models.CharField(max_length=500)),
                ('prepared_key', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(max_length=64)),
                ('report', models.JSONField(default=dict)),
                ('reviewed_for_sharing', models.BooleanField(default=False, help_text='I reviewed the prepared DOCX and its metadata and confirmed it contains no case-specific or confidential material.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matters.matter')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_slug', models.CharField(blank=True, help_text='Empty applies to every template; otherwise use its slug.', max_length=140)),
                ('field', models.CharField(max_length=255)),
                ('source_path', models.CharField(help_text='Path relative to the LegalServer matter payload, e.g. client_address_home.city', max_length=500)),
                ('formatter', models.CharField(choices=[('display', 'Display value'), ('raw', 'Raw value'), ('address', 'Address')], default='display', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizationsettings')),
            ],
            options={
                'ordering': ['template_slug', 'field'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'template_slug', 'field'), name='unique_template_field_mapping')],
            },
        ),
    ]
